CREATE DATABASE IF NOT EXISTS ENTERPRISE_CORTEX_RAG;
USE DATABASE ENTERPRISE_CORTEX_RAG;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS CORTEX;

CREATE OR REPLACE TABLE BRONZE.RAW_CUSTOMERS (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    CITY STRING,
    COUNTRY STRING,
    CREATED_AT STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE STRING,
    STATUS STRING,
    TOTAL_AMOUNT STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_ORDER_ITEMS (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY STRING,
    UNIT_PRICE STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_SUPPORT_TICKETS (
    TICKET_ID STRING,
    CUSTOMER_ID STRING,
    ISSUE_TYPE STRING,
    STATUS STRING,
    DESCRIPTION STRING,
    CREATED_AT STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_DOCUMENT_CHUNKS (
    DOCUMENT_NAME STRING,
    CHUNK_ID STRING,
    TEXT STRING
);