USE DATABASE ENTERPRISE_CORTEX_RAG;
USE SCHEMA CORTEX;

CREATE OR REPLACE TABLE DOCUMENT_CHUNKS (
    DOCUMENT_NAME STRING,
    CHUNK_ID STRING,
    TEXT STRING
);

CREATE OR REPLACE CORTEX SEARCH SERVICE DOCUMENT_SEARCH_SERVICE
ON TEXT
ATTRIBUTES DOCUMENT_NAME
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 hour'
AS (
    SELECT
        DOCUMENT_NAME,
        CHUNK_ID,
        TEXT
    FROM CORTEX.DOCUMENT_CHUNKS
);