USE DATABASE ENTERPRISE_CORTEX_RAG;

CREATE OR REPLACE VIEW GOLD.DIM_CUSTOMER AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CITY,
    COUNTRY
FROM SILVER.CUSTOMERS_CLEAN;

CREATE OR REPLACE VIEW GOLD.DIM_PRODUCT AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    PRICE
FROM SILVER.PRODUCTS_CLEAN;

CREATE OR REPLACE VIEW GOLD.FACT_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    STATUS,
    TOTAL_AMOUNT
FROM SILVER.ORDERS_CLEAN;

CREATE OR REPLACE VIEW GOLD.FACT_ORDER_ITEMS AS
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    QUANTITY * UNIT_PRICE AS LINE_REVENUE
FROM SILVER.ORDER_ITEMS_CLEAN;

CREATE OR REPLACE VIEW GOLD.FACT_SUPPORT_TICKETS AS
SELECT
    TICKET_ID,
    CUSTOMER_ID,
    ISSUE_TYPE,
    STATUS,
    CREATED_AT
FROM SILVER.SUPPORT_TICKETS_CLEAN;