USE DATABASE ENTERPRISE_CORTEX_RAG;

CREATE OR REPLACE VIEW SILVER.CUSTOMERS_CLEAN AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    LOWER(EMAIL) AS EMAIL,
    CITY,
    COUNTRY,
    TRY_TO_TIMESTAMP(CREATED_AT) AS CREATED_AT
FROM BRONZE.RAW_CUSTOMERS;

CREATE OR REPLACE VIEW SILVER.PRODUCTS_CLEAN AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TRY_TO_DECIMAL(PRICE, 10, 2) AS PRICE
FROM BRONZE.RAW_PRODUCTS;

CREATE OR REPLACE VIEW SILVER.ORDERS_CLEAN AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    TRY_TO_DATE(ORDER_DATE) AS ORDER_DATE,
    STATUS,
    TRY_TO_DECIMAL(TOTAL_AMOUNT, 10, 2) AS TOTAL_AMOUNT
FROM BRONZE.RAW_ORDERS;

CREATE OR REPLACE VIEW SILVER.ORDER_ITEMS_CLEAN AS
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    TRY_TO_NUMBER(QUANTITY) AS QUANTITY,
    TRY_TO_DECIMAL(UNIT_PRICE, 10, 2) AS UNIT_PRICE
FROM BRONZE.RAW_ORDER_ITEMS;

CREATE OR REPLACE VIEW SILVER.SUPPORT_TICKETS_CLEAN AS
SELECT
    TICKET_ID,
    CUSTOMER_ID,
    ISSUE_TYPE,
    STATUS,
    DESCRIPTION,
    TRY_TO_TIMESTAMP(CREATED_AT) AS CREATED_AT
FROM BRONZE.RAW_SUPPORT_TICKETS;

CREATE OR REPLACE VIEW SILVER.DOCUMENT_CHUNKS_CLEAN AS
SELECT
    DOCUMENT_NAME,
    CHUNK_ID,
    TEXT
FROM BRONZE.RAW_DOCUMENT_CHUNKS;