apiVersion: v1
kind: Service
metadata:
  name: enterprise-cortex-service
spec:
  type: NodePort
  selector:
    app: enterprise-cortex-streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30501